<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>
    <RootNamespace>CopilotTerminalFeed</RootNamespace>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240311000" />
    <PackageReference Include="Microsoft.Windows.Widgets" Version="1.0.0-experimental1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CopilotTerminalFeed.Server\CopilotTerminalFeed.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\web\**\*" Link="WebContent\%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <AppxManifest Include="Package.appxmanifest" />
  </ItemGroup>

</Project>
